export const MODULE_TOOLTIPS = {
  workers: {
    title_en: '👷 Workers Module',
    title_te: '👷 కార్మికుల మాడ్యూల్',
    intro_en: 'Track all your workers, their attendance, and payments in one place.',
    intro_te: 'మీ కార్మికులు, వారి హాజరు, మరియు చెల్లింపులను ఒక స్థానంలో ట్రాక్ చేయండి.',
    sections: [
      {
        id: 'add-worker',
        title_en: 'Add New Worker',
        title_te: 'కొత్త కార్మికుడిని జోడించండి',
        desc_en: 'Click the + button to create a new worker profile with name, phone, and wage rate.',
        desc_te: 'కొత్త కార్మికుని ప్రొఫైల్ సృష్టించడానికి + బటన్‌ను క్లిక్ చేయండి.',
      },
      {
        id: 'attendance',
        title_en: 'Mark Attendance',
        title_te: 'హాజరు గుర్తించండి',
        desc_en: 'Tap a worker to open their profile and mark daily attendance.',
        desc_te: 'రోజువారీ హాజరును గుర్తించడానికి కార్మికుడిని నొక్కండి.',
      },
      {
        id: 'payment',
        title_en: 'Record Payment',
        title_te: 'చెల్లింపు రికార్డ్ చేయండి',
        desc_en: 'Log each payment made to workers for record keeping.',
        desc_te: 'చెల్లింపుల రికార్డ్‌ను నిర్వహించడానికి ఖర్చులను జోడించండి.',
      },
    ],
  },
  sites: {
    title_en: '🏗️ Sites Module',
    title_te: '🏗️ సైట్‌ల మాడ్యూల్',
    intro_en: 'Organize your construction projects by site. Each site can have its own workers and materials.',
    intro_te: 'సైట్ ద్వారా మీ నిర్మాణ ప్రాజెక్టులను నిర్వహించండి.',
    sections: [
      {
        id: 'create-site',
        title_en: 'Create New Site',
        title_te: 'కొత్త సైట్ సృష్టించండి',
        desc_en: 'Add a project location with site name, address, and start date.',
        desc_te: 'సైట్ పేరు, చిరునామా, మరియు ప్రారంభ తేదీ లేదా సరఫరాదారుల సంపర్కాలను జోడించండి.',
      },
      {
        id: 'assign-workers',
        title_en: 'Assign Workers',
        title_te: 'కార్మికులను నియమించండి',
        desc_en: 'Link workers to a site to track their work on that project.',
        desc_te: 'ఆ ప్రాజెక్టులో కార్మికుల పనిని ట్రాక్ చేయడానికి కార్మికులను సైట్‌కు లింక్ చేయండి.',
      },
      {
        id: 'expenses',
        title_en: 'Track Expenses',
        title_te: 'ఖర్చులను ట్రాక్ చేయండి',
        desc_en: 'Add materials and expenses specific to each site.',
        desc_te: 'ప్రతి సైట్‌కు నిర్దిష్ట వస్తువులు మరియు ఖర్చులను జోడించండి.',
      },
    ],
  },
  attendance: {
    title_en: '📅 Attendance Module',
    title_te: '📅 హాజరు మాడ్యూల్',
    intro_en: 'Mark daily worker attendance and generate reports.',
    intro_te: 'రోజువారీ కార్మికుల హాజరును గుర్తించండి.',
    sections: [
      {
        id: 'daily-attendance',
        title_en: 'Mark Daily Attendance',
        title_te: 'దిన హాజరు గుర్తించండి',
        desc_en: 'Check/uncheck workers present on a given day.',
        desc_te: 'ఇచ్చిన రోజున కార్మికులను ప్రస్తుతమని గుర్తించండి.',
      },
      {
        id: 'attendance-reports',
        title_en: 'View Reports',
        title_te: 'నివేదికలను చూడండి',
        desc_en: 'See attendance summaries and patterns over time.',
        desc_te: 'కాలక్రమేణా హాజరు సంక్షేపాలను చూడండి.',
      },
      {
        id: 'whatsapp-share',
        title_en: 'Share on WhatsApp',
        title_te: 'WhatsApp వద్దకు పంపండి',
        desc_en: 'Share daily attendance with workers via WhatsApp.',
        desc_te: 'హాజరు సమాచారాన్ని WhatsAppద్వారా పంపండి.',
      },
    ],
  },
  money: {
    title_en: '💰 Money Tracking',
    title_te: '💰 డబ్బు ట్రాకింగ్',
    intro_en: 'Monitor all cash flow — wages, expenses, and income.',
    intro_te: 'అన్ని నగదు ప్రవాహం — వేతనాలు, ఖర్చులు, మరియు ఆదాయం.',
    sections: [
      {
        id: 'cash-in',
        title_en: 'Record Income',
        title_te: 'ఆదాయం రికార్డ్ చేయండి',
        desc_en: 'Log money received from clients or projects.',
        desc_te: 'ఖాతాదారుల నుండి పూర్తి చేసిన నిర్మాణం కోసం అందించిన డబ్బు.',
      },
      {
        id: 'expenses',
        title_en: 'Record Expenses',
        title_te: 'ఖర్చులను రికార్డ్ చేయండి',
        desc_en: 'Log all spending — wages, materials, transportation.',
        desc_te: 'వేతనాలు, పదార్థాలు, రవాణా — సభ్యత్వం ఖర్చులు.',
      },
      {
        id: 'cash-summary',
        title_en: 'See Balance',
        title_te: 'సంతులన చూడండి',
        desc_en: 'View total income vs expenses for profit/loss.',
        desc_te: 'లాభం లేదా నష్టం కోసం మొత్తం ఆదాయం వర్సెస్ ఖర్చులను చూడండి.',
      },
    ],
  },
}
