export type Lang = 'en' | 'te'

const en = {
  appTitle: 'Construction Manager', signIn: 'Sign In', signOut: 'Sign Out',
  email: 'Email', password: 'Password', welcome: 'Welcome Back',
  dashboard: 'Dashboard', workers: 'Workers', attendance: 'Daily Attendance',
  sites: 'Sites', privateWorkers: 'Private Workers', privateWork: 'Private Work',
  activeSites: 'Active Sites', addWorker: 'Add Worker', editWorker: 'Edit Worker',
  name: 'Full Name', phone: 'Mobile Number', gender: 'Gender', state: 'State',
  role: 'Role', workType: 'Work Type', wageRates: 'Wage Rates (₹)',
  notes: 'Notes', save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete',
  add: 'Add', search: 'Search...', male: 'Male', female: 'Female',
  mason: 'Mason', helper: 'Helper', centring: 'Centring', brickwork: 'Brickwork',
  telangana: 'Telangana', andhra: 'Andhra', bihar: 'Bihar', allStates: 'All States',
  allTypes: 'All Types', noWorkers: 'No workers found', addSite: 'Add Site',
  siteName: 'Site Name', location: 'Location', ownerName: 'Owner Name',
  ownerPhone: 'Owner Phone', budget: 'Budget (₹)', floors: 'Floors',
  startDate: 'Start Date', status: 'Status', active: 'Active', completed: 'Completed',
  noSites: 'No sites found', markAttendance: 'Mark Attendance',
  shift: 'Shift', absent: 'Absent', advance: 'Advance Given (₹)',
  paymentMode: 'Payment Mode', siteWorked: 'Site Worked', notMarked: 'Not Marked',
  monthly: 'Monthly Summary', totalEarned: 'Total Earned', totalAdvance: 'Total Advance',
  balance: 'Balance', toGive: 'to give', toReceive: 'to receive', settled: 'Settled',
  openingBal: 'Opening Balance', daysWorked: 'Days Worked',
  addContractor: 'Add Contractor', noContractors: 'No contractors',
  owedToWorker: 'Owed to worker', workerOwesYou: 'Worker owes you',
  addPayment: 'Add Payment', paymentHistory: 'Payment History',
  direction: 'Direction', youToWorker: 'You → Worker', workerToYou: 'Worker → You',
  addWork: 'Add Work Entry', noWork: 'No work entries', priceCharged: 'Price Charged (₹)',
  amountPaid: 'Amount Paid (₹)', pending: 'Pending', allSettled: 'All Settled ✓',
  workerAdded: 'Worker added!', workerUpdated: 'Worker updated!',
  siteAdded: 'Site added!', siteUpdated: 'Site updated!', savedOk: 'Saved!',
  required: 'Required', invalidPhone: 'Enter 10-digit number',
  errorLoading: 'Error loading data', deleteConfirm: 'Are you sure? This cannot be undone.',
  personalInfo: 'Personal Info', floorPlans: 'Floor Plans', agreements: 'Agreements',
  elevations: 'Elevations', groundFloor: 'Ground Floor', floor: 'Floor',
  cash: 'Cash', online: 'Online', none: 'None', allWork: 'All', year: 'Year',
  selectYear: 'Select Year', currentYear: 'Current Year', months: [
    'January','February','March','April','May','June',
    'July','August','September','October','November','December'
  ],
  days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
  loading: 'Loading...', refresh: 'Refresh', close: 'Close',
  fullDetails: 'Full Details', viewHistory: 'View History', wokerDetails: 'Worker Details',
  charged: 'Charged', paid: 'Paid', due: 'Due', totalPending: 'Total Pending',
  selectSite: 'Select Site', selectWorker: 'Select Worker', workType2: 'Work Type',
  date: 'Date', allSites: 'All',
}

const te: typeof en = {
  appTitle: 'నిర్మాణ మేనేజర్', signIn: 'లాగిన్ చేయి', signOut: 'లాగ్అవుట్',
  email: 'ఇమెయిల్', password: 'పాస్‌వర్డ్', welcome: 'తిరిగి స్వాగతం',
  dashboard: 'డాష్‌బోర్డ్', workers: 'కార్మికులు', attendance: 'రోజువారీ హాజరు',
  sites: 'సైట్లు', privateWorkers: 'ప్రైవేట్ కార్మికులు', privateWork: 'ప్రైవేట్ పని',
  activeSites: 'చురుకైన సైట్లు', addWorker: 'కార్మికుని జోడించు', editWorker: 'కార్మికుని సవరించు',
  name: 'పూర్తి పేరు', phone: 'మొబైల్ నంబర్', gender: 'లింగం', state: 'రాష్ట్రం',
  role: 'పాత్ర', workType: 'పని రకం', wageRates: 'వేతన రేట్లు (₹)',
  notes: 'గమనికలు', save: 'సేవ్ చేయి', cancel: 'రద్దు', edit: 'సవరించు', delete: 'తొలగించు',
  add: 'జోడించు', search: 'వెతకండి...', male: 'పురుషుడు', female: 'స్త్రీ',
  mason: 'మేస్త్రీ', helper: 'హెల్పర్', centring: 'సెంట్రింగ్', brickwork: 'ఇటుక పని',
  telangana: 'తెలంగాణ', andhra: 'ఆంధ్ర', bihar: 'బీహార్', allStates: 'అన్నీ',
  allTypes: 'అన్నీ', noWorkers: 'కార్మికులు కనుగొనబడలేదు', addSite: 'సైటు జోడించు',
  siteName: 'సైటు పేరు', location: 'లొకేషన్', ownerName: 'యజమాని పేరు',
  ownerPhone: 'యజమాని ఫోన్', budget: 'బడ్జెట్ (₹)', floors: 'అంతస్తులు',
  startDate: 'ప్రారంభ తేదీ', status: 'స్థితి', active: 'చురుకు', completed: 'పూర్తి',
  noSites: 'సైట్లు కనుగొనబడలేదు', markAttendance: 'హాజరు గుర్తించు',
  shift: 'షిఫ్ట్', absent: 'గైర్హాజరు', advance: 'అడ్వాన్స్ (₹)',
  paymentMode: 'చెల్లింపు పద్ధతి', siteWorked: 'పని చేసిన సైటు', notMarked: 'గుర్తించబడలేదు',
  monthly: 'నెలవారీ సారాంశం', totalEarned: 'మొత్తం సంపాదన', totalAdvance: 'మొత్తం అడ్వాన్స్',
  balance: 'బాకీ', toGive: 'ఇవ్వాలి', toReceive: 'తీసుకోవాలి', settled: 'క్లియర్',
  openingBal: 'ప్రారంభ బాకీ', daysWorked: 'పని చేసిన రోజులు',
  addContractor: 'కాంట్రాక్టర్ జోడించు', noContractors: 'కాంట్రాక్టర్లు లేరు',
  owedToWorker: 'కార్మికుడికి ఇవ్వాలి', workerOwesYou: 'కార్మికుడు ఇవ్వాలి',
  addPayment: 'చెల్లింపు జోడించు', paymentHistory: 'చెల్లింపు చరిత్ర',
  direction: 'దిశ', youToWorker: 'మీరు → కార్మికుడు', workerToYou: 'కార్మికుడు → మీరు',
  addWork: 'పని జోడించు', noWork: 'పని వివరాలు లేవు', priceCharged: 'వసూలు ధర (₹)',
  amountPaid: 'చెల్లింపు మొత్తం (₹)', pending: 'పెండింగ్', allSettled: 'అన్నీ క్లియర్ ✓',
  workerAdded: 'కార్మికుడు జోడించబడ్డారు!', workerUpdated: 'కార్మికుడు అప్డేట్ అయ్యారు!',
  siteAdded: 'సైటు జోడించబడింది!', siteUpdated: 'సైటు అప్డేట్ అయింది!', savedOk: 'సేవ్ అయింది!',
  required: 'అవసరం', invalidPhone: '10 అంకెల నంబర్ నమోదు చేయండి',
  errorLoading: 'లోపం సంభవించింది', deleteConfirm: 'ఖచ్చితంగా తొలగించాలా?',
  personalInfo: 'వ్యక్తిగత వివరాలు', floorPlans: 'అంతస్తు ప్లాన్లు', agreements: 'ఒప్పందాలు',
  elevations: 'ఎలివేషన్లు', groundFloor: 'గ్రౌండ్ ఫ్లోర్', floor: 'ఫ్లోర్',
  cash: 'నగదు', online: 'ఆన్‌లైన్', none: 'ఏదీ కాదు', allWork: 'అన్నీ', year: 'సంవత్సరం',
  selectYear: 'సంవత్సరం ఎంచుకోండి', currentYear: 'ఈ సంవత్సరం', months: [
    'జనవరి','ఫిబ్రవరి','మార్చి','ఏప్రిల్','మే','జూన్',
    'జులై','ఆగస్టు','సెప్టెంబర్','అక్టోబర్','నవంబర్','డిసెంబర్'
  ],
  days: ['సోమ','మంగళ','బుధ','గురు','శుక్ర','శని','ఆది'],
  loading: 'లోడ్ అవుతోంది...', refresh: 'రిఫ్రెష్', close: 'మూసివేయి',
  fullDetails: 'పూర్తి వివరాలు', viewHistory: 'చరిత్ర చూడు', wokerDetails: 'కార్మికుడు వివరాలు',
  charged: 'వసూలు', paid: 'చెల్లింపు', due: 'బాకీ', totalPending: 'మొత్తం పెండింగ్',
  selectSite: 'సైటు ఎంచుకోండి', selectWorker: 'కార్మికుని ఎంచుకోండి', workType2: 'పని రకం',
  date: 'తేదీ', allSites: 'అన్నీ',
}

export const strings = { en, te }
export const t = (lang: Lang, key: keyof typeof en): string | string[] => strings[lang][key]
export const ts = (lang: Lang, key: keyof typeof en): string => strings[lang][key] as string
